#include "MainWindow.h"
#include "AboutDialog.h"
#include "SettingsDialog.h"
#include "TrayIcon.h"
#include "backend/ConfigManager.h"
#include "backend/NvibrantController.h"
#include "backend/PresetManager.h"
#include "widgets/DeviceSelector.h"
#include "widgets/MonitorLayout.h"
#include "widgets/PresetList.h"
#include "widgets/VibranceSlider.h"
#include <QCloseEvent>
#include <QApplication>
#include <QComboBox>
#include <QFormLayout>
#include <QGroupBox>
#include <QHBoxLayout>
#include <QInputDialog>
#include <QLabel>
#include <QLineEdit>
#include <QListWidgetItem>
#include <QSystemTrayIcon>
#include <QJsonArray>
#include <QMenuBar>
#include <QMessageBox>
#include <QPushButton>
#include <QShortcut>
#include <QSignalBlocker>
#include <QSet>
#include <QScrollArea>
#include <QStatusBar>
#include <QVBoxLayout>
MainWindow::MainWindow(NvibrantController*c,ConfigManager*cfg,PresetManager*p,QWidget*parent):QMainWindow(parent),controller_(c),config_(cfg),presets_(p){setWindowTitle(tr("nVibrant GUI"));setWindowIcon(QIcon(":/icons/nvibrant-gui.svg"));resize(620,650);setMinimumSize(360,400);auto*central=new QWidget(this);auto*root=new QVBoxLayout(central);root->setSizeConstraint(QLayout::SetMinimumSize);auto*devices=new QGroupBox(tr("Display"),central);auto*form=new QFormLayout(devices);form->setFieldGrowthPolicy(QFormLayout::AllNonFixedFieldsGrow);gpu_=new DeviceSelector;monitor_=new MonitorLayout;auto*monitorScroll=new QScrollArea;monitorScroll->setWidget(monitor_);monitorScroll->setWidgetResizable(true);monitorScroll->setFrameShape(QFrame::NoFrame);monitorScroll->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);monitorScroll->setMinimumHeight(static_cast<QWidget*>(monitor_)->minimumSizeHint().height()+20);slider_=new VibranceSlider;apply_=new QPushButton(tr("Apply"));reset_=new QPushButton(tr("Reset all monitors"));driver_=new QLabel(tr("Detecting…"));auto*actions=new QHBoxLayout;actions->addWidget(apply_);actions->addWidget(reset_);form->addRow(tr("GPU"),gpu_);form->addRow(tr("Monitor setup"),monitorScroll);form->addRow(tr("Digital Vibrance"),slider_);form->addRow(QString(),actions);form->addRow(tr("Driver"),driver_);root->addWidget(devices);
 auto*pg=new QGroupBox(tr("Presets"),central);auto*pl=new QVBoxLayout(pg);presetList_=new PresetList;pl->addWidget(presetList_);auto*pb=new QHBoxLayout;auto*load=new QPushButton(tr("Load"));auto*save=new QPushButton(tr("Save"));auto*del=new QPushButton(tr("Delete"));pb->addWidget(load);pb->addWidget(save);pb->addWidget(del);pl->addLayout(pb);root->addWidget(pg,1);auto*pageScroll=new QScrollArea(this);pageScroll->setWidgetResizable(true);pageScroll->setFrameShape(QFrame::NoFrame);pageScroll->setWidget(central);setCentralWidget(pageScroll);statusBar()->showMessage(tr("Detecting nvibrant and NVIDIA devices…"));connect(presetList_,&QListWidget::currentTextChanged,del,[del,load](const QString &name){const bool selected=!name.isEmpty();del->setEnabled(selected);load->setEnabled(selected);});del->setEnabled(false);load->setEnabled(false);
 auto*file=menuBar()->addMenu(tr("&File"));auto*settings=file->addAction(tr("&Settings…"));file->addSeparator();auto*quit=file->addAction(tr("&Quit"));auto*help=menuBar()->addMenu(tr("&Help"));auto*about=help->addAction(tr("&About"));
 tray_=new TrayIcon(presets_,this);if(QSystemTrayIcon::isSystemTrayAvailable())tray_->show();presets_->configureProcessProfiles(config_->value("processProfiles",QJsonArray{}).toArray());connect(tray_,&TrayIcon::showRequested,this,[this]{showNormal();raise();activateWindow();});connect(tray_,&TrayIcon::quitRequested,this,[this]{quitting_=true;close();qApp->quit();});connect(tray_,&TrayIcon::presetRequested,this,&MainWindow::applyPreset);connect(presets_,&PresetManager::processPresetActivated,this,[this](const QString&n){profileGpu_=gpu_->currentData().toInt();profileMonitor_=monitor_->currentPort();profileValue_=slider_->value();applyPreset(n);statusBar()->showMessage(tr("Process profile applied: %1").arg(n));});connect(presets_,&PresetManager::processPresetEnded,this,[this]{controller_->apply(profileGpu_,profileMonitor_,profileValue_);statusBar()->showMessage(tr("Process profile ended; previous value restored."));});
 connect(quit,&QAction::triggered,this,[this]{quitting_=true;close();qApp->quit();});connect(settings,&QAction::triggered,this,[this]{SettingsDialog(config_,this).exec();});connect(about,&QAction::triggered,this,[this]{AboutDialog(controller_->nvibrantVersion(),this).exec();});connect(load,&QPushButton::clicked,this,[this]{if(auto*i=presetList_->currentItem())loadPreset(i->text());});connect(save,&QPushButton::clicked,this,&MainWindow::savePreset);connect(del,&QPushButton::clicked,this,&MainWindow::removePreset);connect(gpu_,qOverload<int>(&QComboBox::currentIndexChanged),this,[this]{populateMonitors();});connect(monitor_,&MonitorLayout::currentPortChanged,this,[this](int port){const int gpu=gpu_->currentData().toInt();slider_->setValue(pendingValues_.value(pendingKey(gpu,port),controller_->rememberedValue(gpu,port)));});connect(slider_,&VibranceSlider::valuePreviewed,this,[this](int value){if(gpu_->count()&&monitor_->currentPort()>=0)pendingValues_.insert(pendingKey(gpu_->currentData().toInt(),monitor_->currentPort()),value);});connect(apply_,&QPushButton::clicked,this,&MainWindow::applyPending);connect(reset_,&QPushButton::clicked,this,[this]{if(gpu_->count()==0)return;apply_->setEnabled(false);reset_->setEnabled(false);slider_->setValue(0);controller_->resetAll(gpu_->currentData().toInt());});connect(controller_,&NvibrantController::probeCompleted,this,&MainWindow::populateDevices);connect(controller_,&NvibrantController::statusChanged,this,[this](const QString&m,bool e){statusBar()->showMessage(m,8000);if(e){apply_->setEnabled(true);reset_->setEnabled(true);QMessageBox::warning(this,tr("nVibrant"),m);}});connect(controller_,&NvibrantController::applyCompleted,this,[this](int gpu,int port,int value){pendingValues_.remove(pendingKey(gpu,port));apply_->setEnabled(true);reset_->setEnabled(true);if(gpu==gpu_->currentData().toInt())monitor_->setVibrance(port,value);});new QShortcut(QKeySequence::Save,this,[this]{savePreset();});refreshPresets();controller_->probe();}
void MainWindow::populateDevices(){const int selectedGpu=gpu_->count()?gpu_->currentData().toInt():-1;{const QSignalBlocker blocker(gpu_);gpu_->clear();for(const auto&g:controller_->gpus())gpu_->addItem(QString("GPU %1 — %2").arg(g.index).arg(g.name),g.index);const int restored=gpu_->findData(selectedGpu);if(restored>=0)gpu_->setCurrentIndex(restored);}if(!controller_->gpus().isEmpty())driver_->setText(controller_->gpus().first().driver.isEmpty()?tr("Unknown"):controller_->gpus().first().driver);populateMonitors();QSet<QString> valid;for(auto it=controller_->monitors().cbegin();it!=controller_->monitors().cend();++it)for(const auto&m:it.value())if(m.connected)valid.insert(pendingKey(it.key(),m.port));for(auto it=pendingValues_.begin();it!=pendingValues_.end();)if(!valid.contains(it.key()))it=pendingValues_.erase(it);else++it;statusBar()->showMessage(gpu_->count()?tr("Display setup updated"):tr("No NVIDIA GPU"));}
void MainWindow::populateMonitors(){int g=gpu_->currentData().toInt();QVector<MonitorTile> tiles;for(const auto&m:controller_->monitors().value(g))if(m.connected)tiles.append({m.port,m.type,controller_->rememberedValue(g,m.port)});monitor_->setMonitors(tiles);const int port=monitor_->currentPort();slider_->setEnabled(port>=0);apply_->setEnabled(port>=0);reset_->setEnabled(port>=0);slider_->setValue(port>=0?pendingValues_.value(pendingKey(g,port),controller_->rememberedValue(g,port)):0);}
void MainWindow::refreshPresets(){presetList_->clear();for(const auto&p:presets_->presets())presetList_->addItem(p.name);tray_->refreshPresets();}
void MainWindow::savePreset(){bool ok=false;QString n=QInputDialog::getText(this,tr("Save preset"),tr("Preset name:"),QLineEdit::Normal,{},&ok).trimmed();if(!ok||n.isEmpty())return;presets_->upsert({n,slider_->value(),monitor_->currentPort(),gpu_->currentData().toInt()});QString e;if(!presets_->save(&e))QMessageBox::critical(this,tr("Preset error"),e);else refreshPresets();}
void MainWindow::removePreset(){auto*i=presetList_->currentItem();if(!i)return;presets_->remove(i->text());QString e;if(!presets_->save(&e))QMessageBox::critical(this,tr("Preset error"),e);else refreshPresets();}
void MainWindow::applyPreset(const QString&name){for(const auto&p:presets_->presets())if(p.name==name){int gi=gpu_->findData(p.gpu);if(gi>=0)gpu_->setCurrentIndex(gi);if(monitor_->hasPort(p.monitor))monitor_->setCurrentPort(p.monitor);slider_->setValue(p.vibrance);applyCurrent(p.vibrance);return;}}
void MainWindow::applyCurrent(int v){if(gpu_->count()==0||monitor_->currentPort()<0)return;apply_->setEnabled(false);reset_->setEnabled(false);controller_->apply(gpu_->currentData().toInt(),monitor_->currentPort(),v);}
QString MainWindow::pendingKey(int gpu,int port)const{return QString::number(gpu)+':'+QString::number(port);}
void MainWindow::applyPending(){if(gpu_->count()==0)return;const int gpu=gpu_->currentData().toInt();QHash<int,int> values;const QString prefix=QString::number(gpu)+':';for(auto it=pendingValues_.cbegin();it!=pendingValues_.cend();++it)if(it.key().startsWith(prefix))values.insert(it.key().mid(prefix.size()).toInt(),it.value());if(values.isEmpty()){statusBar()->showMessage(tr("No pending monitor changes."),3000);return;}apply_->setEnabled(false);reset_->setEnabled(false);controller_->applyValues(gpu,values);}
void MainWindow::loadPreset(const QString&name){for(const auto&p:presets_->presets())if(p.name==name){int gi=gpu_->findData(p.gpu);if(gi>=0)gpu_->setCurrentIndex(gi);if(!monitor_->hasPort(p.monitor)){statusBar()->showMessage(tr("The monitor saved in this preset is not connected."),5000);return;}monitor_->setCurrentPort(p.monitor);pendingValues_.insert(pendingKey(p.gpu,p.monitor),p.vibrance);slider_->setValue(p.vibrance);applyCurrent(p.vibrance);statusBar()->showMessage(tr("Preset loaded and applied."),3000);return;}}
void MainWindow::closeEvent(QCloseEvent*e){if(!quitting_&&config_->value("closeToTray",true).toBool()&&tray_->isVisible()){hide();tray_->showMessage(tr("nVibrant GUI"),tr("The application is still running in the tray."));e->ignore();return;}QMainWindow::closeEvent(e);}
