if(NOT EXISTS "${CMAKE_BINARY_DIR}/install_manifest.txt")
  message(FATAL_ERROR "No install manifest found")
endif()
file(STRINGS "${CMAKE_BINARY_DIR}/install_manifest.txt" installed_files)
foreach(installed_file IN LISTS installed_files)
  if(EXISTS "$ENV{DESTDIR}${installed_file}" OR IS_SYMLINK "$ENV{DESTDIR}${installed_file}")
    file(REMOVE "$ENV{DESTDIR}${installed_file}")
  endif()
endforeach()
